// ============================================================
// scripts/lib/code-writer.ts
//
// Utility for writing generated files.
// Ensures output directories exist, tracks written vs skipped.
// ============================================================

import fs from "fs";
import path from "path";

export interface WriteResult {
  written: string[];
  skipped: string[];
}

export class CodeWriter {
  private written: string[] = [];
  private skipped: string[] = [];

  /**
   * Write a file. Creates parent directories automatically.
   * If the file already exists and force=false, skips it.
   */
  write(filePath: string, content: string, force = true): void {
    const dir = path.dirname(filePath);
    fs.mkdirSync(dir, { recursive: true });

    if (!force && fs.existsSync(filePath)) {
      this.skipped.push(filePath);
      return;
    }

    fs.writeFileSync(filePath, content, "utf-8");
    this.written.push(filePath);
  }

  getSummary(): { written: number; skipped: number } {
    return { written: this.written.length, skipped: this.skipped.length };
  }

  summary(): WriteResult {
    return {
      written: this.written,
      skipped: this.skipped,
    };
  }

  printSummary(): void {
    console.log(`\n  ✓ ${this.written.length} written, ${this.skipped.length} skipped`);
    for (const f of this.written) {
      console.log(`    + ${f}`);
    }
    for (const f of this.skipped) {
      console.log(`    ~ ${f} (skipped)`);
    }
  }
}

// ─── Helpers ─────────────────────────────────────────────────

/** Convert camelCase or kebab-case to PascalCase */
export function toPascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (c) => c.toUpperCase());
}

/** e.g. grantRole → GrantRole, ADMIN_ROLE → AdminRole (for `useAdminRole` / filenames). */
export function toHookBaseName(name: string): string {
  if (name.includes("_")) {
    return name
      .split("_")
      .filter(Boolean)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
      .join("");
  }
  return toPascalCase(name);
}

/** Convert PascalCase or camelCase to kebab-case */
export function toKebabCase(str: string): string {
  return str
    .replace(/([A-Z])/g, "-$1")
    .toLowerCase()
    .replace(/^-/, "");
}

/** Capitalise first letter */
export function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/** Auto-generated file header comment */
export function autoGenHeader(scriptName = "scripts/generate.ts"): string {
  return `// ============================================================
// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Generated by: ${scriptName}
// To regenerate: yarn generate
// ============================================================\n\n`;
}

/** Standalone write (back-compat for callers that do not use CodeWriter). */
export function writeFile(filePath: string, content: string): void {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
}
